---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/ElisaOyj/runasuser-admission-controller

steps:
  - name: test-and-build
    image: golang:1.15
    pull: always
    commands:
      - make deps
      - make ensure
      - make test
      - make build-linux-amd64

  - name: pr-build
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/elisaoyj/runasuser-admission-controller
      tags: latest
      dry_run: true
    when:
      branch:
        excludes:
          - master
      event:
        - pull_request

  - name: publish
    image: plugins/docker
    settings:
      password:
        from_secret: docker_password
      registry: quay.io
      repo: quay.io/elisaoyj/runasuser-admission-controller
      tags:
        - "${DRONE_COMMIT_SHA}"
        - latest
      username:
        from_secret: docker_username
    when:
      branch:
        - master
      event:
        - push
